// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://houpsebfywxdsytqvvqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvdXBzZWJmeXd4ZHN5dHF2dnFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NTQzODMsImV4cCI6MjA2NDIzMDM4M30.wIM44QF5tPPrxuuMWOVPLQ29qGsg1eCJd5uvnQgVQcs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);